sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/OpenAppleProject/openappleproject.github.io"
  
title: Open Apple Project
description: Open Apple is a project that aims to opensource and write documentation for as many apple related things as possible
